name: Workflow

on:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'

jobs:
  build:
    name: Lint, format, test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Lint 💅
        run: pnpm lint

      - name: Format 🔍
        run: pnpm format:check

      - name: Test 🧪
        run: pnpm test --passWithNoTests

      - name: Build 🔨
        run: pnpm build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  push-dist-files:
    name: Commit dist files
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Commit dist files
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update dist files'
          add: 'dist --force'

  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Test Action
        uses: ./

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: test-action
          client-payload: '{"ref": "${{ github.ref }}"}'
